"""``jason collection KEY``: a collection's summary page (``jason.tasks.collection_pages``).

A collection is a set of documents reviewed together (``jason review --collections`` lists them: a legal case's file is
one). ``jason collection KEY`` prints its summary: what the collection is and the specification's record of the
matter, its files and how each was read, what is missing or unread, the open questions, the conflicts of fact, and
the chronology of what the documents say, each statement with its file and passage. ``KEY`` is the collection's key
or its catalog (``case-<key>``); naming a legal case opens its confidential files, as the other commands do. With no
key the collections are listed.

``--write`` saves the page as ``data/collections/<key>/summary.md`` under the store lock; without it nothing is
written. ``jason index --build`` then indexes the page in the collection's own catalog as a page jason generated,
confidential when the collection is. ``--json`` prints the result as JSON.

The page is generated by rule from the stores: no model, no network. It is a summary, not the record, and it is
written again whole each time, never edited.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any, Callable


def cmd_collection(args: argparse.Namespace) -> int:
    from jason.commands.chronology import _say
    from jason.commands.review import collection_lines
    from jason.community import community as active
    from jason.community.document_collections import collection as named
    from jason.config import data_dir as active_data_dir
    from jason.tasks import collection_pages

    community = active()
    data = active_data_dir(getattr(args, "env", None))
    if not args.key:
        lines = collection_lines(community, data)
        print("\n".join(lines) if lines else "no collections: the specification sets no legal case with a case file")
        return 0
    found = named(community, args.key)
    if found is None:
        print(f"no collection {args.key!r}: jason collection lists them", file=sys.stderr)
        return 2
    try:
        summary = collection_pages.summarize(community, data, found)
    except FileNotFoundError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    if args.json:
        print(json.dumps(summary.as_dict(), indent=1))
    elif not args.write:
        for line in summary.markdown().splitlines():
            _say(line)
    if args.write:
        path = collection_pages.write(data, summary)
        print(f"wrote {path}" + (" (confidential: for directors and counsel)" if summary.confidential else "")
              + "; jason index --build indexes it", file=sys.stderr)
    return 0


def register(sub: Any, add_common: Callable[[Any], None], agent_factory: Callable[[Any], Any]) -> None:
    p = sub.add_parser("collection", help="A collection's summary page: its files and how each was read, what is "
                                          "missing, the open questions, the conflicts, and the chronology, each "
                                          "statement with its source (a summary, not the record)")
    add_common(p)
    p.add_argument("key", nargs="?", default="", metavar="KEY",
                   help="the collection's key or its catalog (case-KEY); without it the collections are listed")
    p.add_argument("--write", action="store_true",
                   help="save the page as data/collections/<key>/summary.md; without it nothing is written")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_collection)
