"""Drive folder globs and the folders sync must skip."""

from jason.community.base import ExcludedFolder, SyncRule
from jason.community.documents import KindRule
from jason.community.symbols import AssociationRecord, DocumentKind, DocumentRule, PayhoaFolder, PublicDrive

RULES: tuple[SyncRule, ...] = (
    SyncRule(DocumentRule.GOVERNING_ROOT, "Governing Documents", PublicDrive.GOVERNING_DOCUMENTS, "{CCRs,CCRs.*,Bylaws,Bylaws.*,Articles of Incorporation.pdf,Owner's Manual*}", PayhoaFolder.GOVERNING_DOCUMENTS, records=(AssociationRecord.GOVERNING_DOCUMENTS,)),
    SyncRule(DocumentRule.ELECTION_RULES, "Governing Documents", PublicDrive.GOVERNING_DOCUMENTS, "Election Rules*", PayhoaFolder.ELECTIONS, records=(AssociationRecord.GOVERNING_DOCUMENTS,)),
    SyncRule(DocumentRule.ANNEXATIONS, "Annexations", PublicDrive.ANNEXATIONS, "Annexation - Phase *", PayhoaFolder.ANNEXATIONS, records=(AssociationRecord.GOVERNING_DOCUMENTS,)),
    SyncRule(DocumentRule.POLICIES, "Governing Documents/Policies", PublicDrive.POLICIES, "*", PayhoaFolder.POLICIES, ("old/**",), records=(AssociationRecord.GOVERNING_DOCUMENTS,)),
    SyncRule(DocumentRule.RESOLUTIONS, "Governing Documents/Resolutions", PublicDrive.RESOLUTIONS, "*", PayhoaFolder.RESOLUTIONS),
    SyncRule(DocumentRule.DRE_REPORTS, "California BRE", PublicDrive.DRE_REPORTS, "*SA-*.pdf", PayhoaFolder.DRE_PUBLIC_REPORTS),
    SyncRule(DocumentRule.GRANT_DEEDS, "Deeds", PublicDrive.DEEDS, "GD *", PayhoaFolder.GRANT_DEEDS),
    SyncRule(DocumentRule.PLANS, "Plans", PublicDrive.PLANS, "{Condominium Plan *,DR18-052_*,Paint Schedule.png}", PayhoaFolder.PLANS),
    SyncRule(DocumentRule.MAPS, "Maps", PublicDrive.MAPS, "{Assessors Parcel Map.pdf,Final Map of JMA North Natomas Parcel 4.pdf,JMA Property High Density Map.pdf,Sanborn Map Report 4840406.3.pdf}", PayhoaFolder.MAPS),
    SyncRule(DocumentRule.INSURANCE_CURRENT, "Insurance", PublicDrive.INSURANCE, "{FLOOD POLICY *,Certificate of Insurance*,Personal Insurance Checklist*,RCBAP Lender rules.pdf,Custom evidence of insurance*}", PayhoaFolder.INSURANCE, also_seen_in="Email Attachments/", records=(AssociationRecord.EXECUTED_CONTRACT,)),
)

KIND_RULES: tuple[KindRule, ...] = (
    # Match order is part of the rule. The platform's blank templates come first: they are not association records.
    KindRule(DocumentKind.TEMPLATE, ("*",), paths=("payhoa resources and templates*",)),
    KindRule(DocumentKind.AUDIO, ("*.mp3", "*.m4a", "*.wav")),
    # The prior manager's archive in Drive (My Drive/The Helsing Group/Archives from Prior Management), by folder. Its
    # "Statement" folders hold owners' account statements, named by the manager's resident account id.
    KindRule(DocumentKind.OWNER_STATEMENT, ("*.pdf",), paths=("*/archives from prior management/statement/*",
                                                             "*/archives from prior management/statements - ad hoc/*")),
    KindRule(DocumentKind.VIOLATION_NOTICE, ("*.pdf",), paths=("*/archives from prior management/violationnotice/*",)),
    KindRule(DocumentKind.FINANCIAL_STATEMENT, ("*.pdf",), paths=("*/archives from prior management/financial reports/*",)),
    # Its vendor invoices carry the vendor code in the name: "RM_CITSACRA" is the City of Sacramento's utility bill.
    KindRule(DocumentKind.UTILITY_BILL, ("*RM_CITSACRA*", "*SMUD*"), paths=("*/archives from prior management/vendor invoices/*",)),
    KindRule(DocumentKind.INVOICE, ("*.pdf",), paths=("*/archives from prior management/vendor invoices/*",)),
    KindRule(DocumentKind.UTILITY_BILL, ("*.pdf",), paths=("*/financials/*/invoices/smud/*", "*/financials/*/invoices/water/*")),
    KindRule(DocumentKind.INVOICE, ("*.pdf",), paths=("*/financials/*/invoices/*",)),
    KindRule(DocumentKind.PROPOSAL, ("*.pdf",), paths=("*/proposals / estimates/*",)),
    KindRule(DocumentKind.RESALE_DISCLOSURE, ("Resale - *.pdf", "Questionnaire - *.pdf")),
    KindRule(DocumentKind.CORRESPONDENCE, ("Welcome Letter *",)),
    KindRule(DocumentKind.SECURITY_REPORT, ("DAILY-REPORT-*",)),
    KindRule(DocumentKind.EXECUTIVE_SESSION, ("Executive Session*",)),
    KindRule(DocumentKind.AMENDMENT, ("*Amendment*",)),
    KindRule(DocumentKind.DECLARATION, ("CCRs", "CCRs.*", "CCRs 2007*", "CCRs 20070912*")),
    KindRule(DocumentKind.BYLAWS, ("Bylaws", "Bylaws.*")),
    KindRule(DocumentKind.ARTICLES, ("Articles of Incorporation.pdf", "* - Articles of Incorporation*")),
    KindRule(DocumentKind.ELECTION_RULES, ("Election Rules*",)),
    KindRule(DocumentKind.OPERATING_RULES, ("Owner's Manual*", "owners-manual-and-rules*")),
    KindRule(DocumentKind.ANNEXATION, ("Annexation - Phase *",)),
    # The Annexations folder holds the declarations of annexation, some under the recorder's own title ("ACA 8 ...").
    KindRule(DocumentKind.ANNEXATION, ("*",), PayhoaFolder.ANNEXATIONS),
    # Insurance before policies: a flood policy is not a board policy.
    KindRule(DocumentKind.INSURANCE_POLICY, ("FLOOD POLICY *", "Flood Policy *", "Coverage Limits*")),
    KindRule(DocumentKind.EVIDENCE_OF_INSURANCE, ("Certificate of Insurance*", "Custom evidence of insurance*")),
    KindRule(DocumentKind.POLICY, ("*",), PayhoaFolder.POLICIES),
    KindRule(DocumentKind.POLICY, ("* Policy.pdf", "* Policy *.pdf", "* Policy", "Fine Schedule*")),
    KindRule(DocumentKind.RESOLUTION, ("*",), PayhoaFolder.RESOLUTIONS),
    KindRule(DocumentKind.RESOLUTION, ("*Resolution - *",)),
    KindRule(DocumentKind.MINUTES, ("Minutes*", "DRAFT Minutes*")),
    KindRule(DocumentKind.AGENDA, ("Agenda*", "*Agenda - *", "*Notice and agenda*")),
    KindRule(DocumentKind.COMMITTEE_REPORT, ("*Committee Report*",)),
    KindRule(DocumentKind.TREASURER_REPORT, ("Treasurer*Report*",)),
    KindRule(DocumentKind.BANK_STATEMENT, ("*-statements-*",)),
    KindRule(DocumentKind.CORRESPONDENCE, ("*-noticesandletters-*",)),
    KindRule(DocumentKind.CORRESPONDENCE, ("Contact Information*", "Flock-Search-Result-*")),
    KindRule(DocumentKind.NOTICE, ("ALPR Safe List*",)),
    KindRule(DocumentKind.CORRESPONDENCE, ("*Newsletter*", "*Instructions to Escrow*", "Instructions for *", "Welcome to *", "How to obtain *", "*Insurance Checklist*", "*Lender rules*", "*Poster*", "*Neighborhood Guide*")),
    KindRule(DocumentKind.FINANCIAL_STATEMENT, ("*Financial Statements*",)),
    KindRule(DocumentKind.CONTRACT, ("*Review & Tax EL*",)),
    KindRule(DocumentKind.FINANCIAL_REVIEW, ("Financial Review *", "*Tax Review*")),
    KindRule(DocumentKind.RESERVE_STUDY, ("Reserve Study*",)),
    KindRule(DocumentKind.BUDGET, ("*Budget*",)),
    KindRule(DocumentKind.ANNUAL_DISCLOSURE, ("Annual Disclosures*",)),
    KindRule(DocumentKind.ANNUAL_DISCLOSURE, ("Insurance Summary*", "Insuance Summary*")),
    KindRule(DocumentKind.TAX_BILL, ("Bill 2011*", "Delinquent Tax Bills*")),
    KindRule(DocumentKind.ELECTION_RESULTS, ("*Election Results*",)),
    KindRule(DocumentKind.BALLOT, ("Ballot*",)),
    # The balcony (SB 326) report by name; the proposal and invoice for it ("SB326 - California Deck Inspection") are not.
    KindRule(DocumentKind.ELEVATED_ELEMENT_INSPECTION, ("*SB 326 Report*", "*SB326 Report*", "*SB-326 Report*",
                                                        "*Elevated Element*Report*", "*Balcony Inspection Report*")),
    # Insurance claims, before the proposal and invoice rules ("ESTIMATE FOR REPAIRS 5021880419-1" is the carrier's estimate).
    KindRule(DocumentKind.LOSS_RUN, ("*Loss Run*", "*Loss run*", "*loss run*")),
    KindRule(DocumentKind.CLAIM_LETTER, ("*Claim Outcome*", "*RE CLAIM*", "*Status letter to insured*", "*Primacy Letter*",
                                         "*Acknowledgement Letter*", "*Acknowledgment Letter*", "*Claim info*", "*Liability Claim*")),
    KindRule(DocumentKind.CLAIM_PAYMENT, ("*Statement of loss*", "echeque*", "*eCheque*")),
    KindRule(DocumentKind.CLAIM_AUTHORIZATION, ("*WORK AUTHORIZATION*", "*Work Authorization*", "* ATR.pdf", "*Cert of satisfaction*",
                                                "*Certificate of Satisfaction*", "*Project Tracker*")),
    KindRule(DocumentKind.CLAIM_ESTIMATE, ("ESTIMATE FOR REPAIRS *", "*Mitigation estimate*", "*Mitigation Estimate*")),
    KindRule(DocumentKind.POLICE_REPORT, ("*Police Report*", "*police report*")),
    KindRule(DocumentKind.MANAGER_CASE_REPORT, ("*Case Performance*",)),
    KindRule(DocumentKind.PROPOSAL, ("*Proposal*", "* - Quote*")),
    KindRule(DocumentKind.INVOICE, ("Inv_*", "*Invoice*")),
    KindRule(DocumentKind.INSPECTION_REPORT, ("*inspection report*",)),
    # RoofChecks' reports: "Roof Inspection - 2026 Report.pdf" and its signed copy "Good Life Roof Inspection / Repairs - ...".
    KindRule(DocumentKind.INSPECTION_REPORT, ("Roof Inspection - * Report*", "*Roof Inspection*Repairs*")),
    KindRule(DocumentKind.SETTLEMENT, ("*Settlement Agreement*",)),
    KindRule(DocumentKind.LEGAL_CORRESPONDENCE, ("* - LTR to *",)),
    KindRule(DocumentKind.LEGAL_BRIEF, ("Mediation Brief*",)),
    KindRule(DocumentKind.LEGAL_CORRESPONDENCE, ("Request to Meet and Confer*",)),
    KindRule(DocumentKind.RECORDED_LIEN, ("MECHANICS LIEN *", "BOND FOR RELEASE OF LIEN *", "Notice of claim of lien*")),
    KindRule(DocumentKind.DELINQUENCY_NOTICE, ("*Pre-Lien Notice*", "Notice of Default and Demand*")),
    KindRule(DocumentKind.DELINQUENCY_NOTICE, ("Reimbursement Assessment - *",)),
    # "Annual Membership Meeting - 2025.pdf" is the annual meeting's minutes; its agenda is "Annual Membership Meeting Agenda - *".
    KindRule(DocumentKind.MINUTES, ("Annual Membership Meeting - *",)),
    KindRule(DocumentKind.VIOLATION_NOTICE, ("Notice of Violation*",)),
    KindRule(DocumentKind.NOTICE, ("Notice - *", "Notice of *", "Disclosure Regarding Pending Litigation*", "Pending Litigation Disclosure*", "Pre-Ballot-Notice*")),
    KindRule(DocumentKind.OWNER_HISTORY, ("Full Owner History*",)),
    KindRule(DocumentKind.MEMBERSHIP_LIST, ("members.csv",)),
    KindRule(DocumentKind.FORM, ("*",), paths=("governing documents/forms/*", "resident registration forms/*")),
    KindRule(DocumentKind.FORM, ("*Form.pdf", "Petition requesting*", "Change of Address*")),
    KindRule(DocumentKind.CONDOMINIUM_PLAN, ("Condominium Plan *",)),
    KindRule(DocumentKind.PLAN_SET, ("DR18-052_*",)),
    KindRule(DocumentKind.PLAN_SET, ("*",), PayhoaFolder.PLANS),
    KindRule(DocumentKind.MAP, ("Assessors Parcel Map*", "*Map of *", "* Map.pdf", "Sanborn Map*")),
    KindRule(DocumentKind.MAP, ("*",), PayhoaFolder.MAPS),
    KindRule(DocumentKind.GRANT_DEED, ("GD *", "*deed*")),
    KindRule(DocumentKind.DRE_REPORT, ("*SA-*.pdf",)),
    KindRule(DocumentKind.LEASE, ("*Lease Agreement*",)),
    # The developer's DRE securities, before the general contract rules ("Security Agreement Phase 1" is not a vendor contract).
    KindRule(DocumentKind.SECURITY_AGREEMENT, ("*Security Agreement*",)),
    KindRule(DocumentKind.SUBSIDY_AGREEMENT, ("*Subsidy Agreement*",)),
    KindRule(DocumentKind.BOND_RELEASE, ("*Bond Release*", "Letter Re Bond*", "*Requesting Release of * Bonds*", "*Release of Bonds*")),
    KindRule(DocumentKind.SURETY_BOND, ("Mystique Bond*", "* Bond # *", "* Bond No*")),
    KindRule(DocumentKind.CONTRACT, ("*",), PayhoaFolder.CONTRACTS),
    KindRule(DocumentKind.CONTRACT, ("*Agreement*", "*Contract*")),
    KindRule(DocumentKind.LEASE, ("*",), PayhoaFolder.LEASE_AGREEMENTS),
    KindRule(DocumentKind.IMAGE, ("*.jpg", "*.jpeg", "*.png", "*.heic", "*.gif")),
)

EXCLUDED: tuple[ExcludedFolder, ...] = (
    ExcludedFolder("Governing Documents/Audio Book", PublicDrive.AUDIO_BOOK.value, "about 2049 audio files, no PayHOA name match"),
    ExcludedFolder("Governing Documents/Proposed", PublicDrive.PROPOSED.value, "drafts, not in PayHOA"),
    ExcludedFolder("Governing Documents/Applications", PublicDrive.APPLICATIONS.value, "parking permit forms, not in the PayHOA library"),
    ExcludedFolder("Governing Documents/Policies/old", PublicDrive.POLICIES_OLD.value, "superseded policies"),
    ExcludedFolder("Plans/John Laing Homes", PublicDrive.JOHN_LAING.value, "about 150 files, no PayHOA name match"),
    ExcludedFolder("Plans/Watt Communities (New Buildings)", PublicDrive.WATT.value, "no PayHOA name match"),
)
