"""A collection's summary page: one generated page that gathers what the stores hold about a set of documents.

A collection (``jason.community.document_collections``) is a set of documents reviewed together: a legal case's file,
and later a vendor's file or a meeting's packet. ``summarize`` reads the stores and gives a ``Summary``; its
``markdown`` is the page, in these sections:

1. **What this collection is**: its title, kind, key, and what its material is.
2. **The collection's context**, titled as the collection titles it. For a legal case this is the specification's
   record of the matter: its forum, role, and status, then its events, then its duties, as the ``LegalCase`` record
   holds them. They are the specification's entries, kept in their own section and never merged with what a document
   says.
3. **Sources: the collection's files**: each file with its kind, its standing, how its words were read (the text
   layer, an OCR engine, a vision model, or not at all), the pages no reader gave words for, and how many dated
   statements it gave. A file the collection's rule holds back is counted, never named.
4. **What is missing or unread**: files with no text, image pages unread, words an OCR engine read, files that gave
   no dated statement, mentions of a month and a day with no year, and what the conflict rules could not compare.
5. **Open questions**: the facts the stores leave undetermined. jason answers none.
6. **Conflicts of fact** (``fact_conflicts``): every side kept, neither picked.
7. **Chronology: what the documents say** (``chronology``): the documents' own dates apart from the dates they speak
   about, each statement quoted with its file and passage.

Every statement names the file and passage it rests on, and nothing here finds that an event happened: it says only
that a document says so. The page opens with the header every generated collection page carries
(``chronology.page_header``): generated by jason on a date, by rule, from the documents listed; a summary, not the
record; confidential when the collection is. No model and no network.

``write`` saves ``data/collections/<key>/summary.md`` under the store lock. The page is written whole each time and
never edited: the same stores give the same page, apart from the line that carries the date. ``index_sources`` gives
each collection's pages to the passage index in the collection's own catalog, with the standing ``page`` and the
collection's confidentiality, so a search of the catalog finds the summary and labels it a summary. A collection's
scope leaves its pages out (``document_collections.NOT_MEMBERS``), so the page is never read back as a document.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Iterable, Sequence

from jason.community import chronology as ch
from jason.community import fact_conflicts as fc
from jason.community.document_collections import (CHRONOLOGY_SECTION, SUMMARY_LABEL, SUMMARY_PAGE, Collection,
                                                  CollectionKind, case_matter, context_heading, duty_line)
from jason.community.passage_index import IndexFile, Standing

WHAT = "What this collection is"
FILES = "Sources: the collection's files"
MISSING = "What is missing or unread"
QUESTIONS = "Open questions"
CONFLICTS = "Conflicts of fact"
CHRONOLOGY = CHRONOLOGY_SECTION
OWN_DATES = "The documents' own dates"
OTHER_DATES = "Dates at a document's head, in a header inside it, or in its file's name"
ABOUT_DATES = "Dates the documents speak about"
RECORDED_EVENTS = "Events the specification records"
RECORDED_DUTIES = "Duties the specification records"
NOT_READ = "not read"
AS_INDEXED = "text, as the index holds it"
AS_FETCHED = "text, as it was fetched"

CAVEATS: tuple[str, ...] = (
    "This page is a summary jason generated from the stores. It is never quoted in place of the documents it lists: "
    "quote the document, from the file.",
    "The page is written again whole from the stores each time. A change made to it by hand is lost, and a correction "
    "belongs in the store it came from.",
    "A file with no text gave this page nothing. What it says is not here, and the page does not say that it is "
    "silent.",
)


@dataclass(frozen=True)
class FileRow:
    """One file of the collection that is not held back: what it is, and how its words were read."""

    name: str                         # as the collection's folder names it; a file known only to the index, by its name there
    kind: str = ""                    # its document kind in the index; empty when it has none
    standing: Standing | None = None  # None: not in the index
    how: str = ""                     # how its words were read, or that they were not and why
    why: str = ""                     # why it has no text
    has_text: bool = False
    indexed: bool = False
    statements: int = 0               # dated statements it gave the chronology
    pages: int = 0
    unread_pages: int = 0             # pages that are images no reader gave words for
    may_misread: bool = False         # an OCR engine or a vision model read some of its words
    confidential: bool = False
    path: str = ""                    # the indexed text's path, to tie a statement to its file

    def as_dict(self) -> dict[str, Any]:
        return {"file": self.name, "kind": self.kind, "standing": self.standing.value if self.standing else None,
                "howRead": self.how, "hasText": self.has_text, "indexed": self.indexed,
                "datedStatements": self.statements, "pages": self.pages, "pagesUnread": self.unread_pages,
                "mayMisread": self.may_misread, "confidential": self.confidential}


@dataclass(frozen=True)
class Gap:
    """One thing the page could not read or does not hold, with how many files or mentions it counts."""

    key: str
    text: str
    count: int = 1

    def as_dict(self) -> dict[str, Any]:
        return {"key": self.key, "count": self.count, "text": self.text}


def case_of(community: Any, collection: Collection) -> Any | None:
    """The specification's legal case behind a legal case's collection, or None."""
    if collection.kind is not CollectionKind.LEGAL_CASE:
        return None
    return next((case for case in community.legal_cases() if case.key == collection.key), None)


def _under(path: str, data_dir: Path) -> str:
    """A file's path under the data directory, as the index names it."""
    try:
        return Path(path).resolve().relative_to(Path(data_dir).resolve()).as_posix()
    except ValueError:
        return Path(path).as_posix()


def _read_how(found: Any) -> tuple[str, bool]:
    """(how a case file's words were read, whether a reader that may misread read some) for a file with text."""
    from jason.tasks.case_files import FileState, ReadMethod

    if found.state is FileState.TEXT:
        return AS_FETCHED, False
    extract = found.extract
    if extract is None:
        return found.why or AS_FETCHED, False
    read_scans = extract.scan_pages - extract.unread_pages
    misread = extract.method in (ReadMethod.OCR, ReadMethod.VISION) or (
        extract.method is ReadMethod.TEXT_LAYER and read_scans > 0)
    return extract.label, misread


def file_rows(data_dir: Path, collection: Collection, indexed: Sequence[ch.SourceFile], inventory: Any | None) -> tuple[FileRow, ...]:
    """The collection's files that are not held back. With an inventory of the collection's folder
    (``case_files.inventory``) each file of the folder is a row, tied to its text in the index; a file the index holds
    that the folder does not account for is a row of its own. Without one, the rows are the index's files."""
    by_rel = {_under(f.path, data_dir): f for f in indexed}
    rows: list[FileRow] = []
    taken: set[str] = set()
    for found in (inventory.files if inventory is not None else ()):
        rel = f"{collection.folder}/{found.text}" if found.text else ""
        source = by_rel.get(rel) if rel else None
        if source is not None:
            taken.add(rel)
        extract = found.extract
        how, misread = _read_how(found) if found.readable else (f"{NOT_READ}: {found.why}", False)
        rows.append(FileRow(
            found.name, kind=source.kind if source else "", standing=source.standing if source else None, how=how,
            why="" if found.readable else found.why, has_text=found.readable, indexed=source is not None, statements=source.statements if source else 0,
            pages=extract.pages if extract else 0, unread_pages=extract.unread_pages if extract else 0,
            may_misread=misread, confidential=bool(source and source.confidential), path=source.path if source else ""))
    for rel, source in by_rel.items():
        if rel in taken:
            continue
        rows.append(FileRow(source.file, kind=source.kind, standing=source.standing,
                            how=AS_INDEXED + (f" ({source.context})" if source.context else ""), has_text=True,
                            indexed=True, statements=source.statements, confidential=source.confidential,
                            path=source.path))
    rows.sort(key=lambda r: (not r.has_text, r.name.lower(), r.name))
    return tuple(rows)


def _names(rows: Iterable[FileRow]) -> str:
    return "; ".join(row.name for row in rows)


def _count(n: int, noun: str) -> str:
    return f"{n} {noun}" if n == 1 else f"{n} {noun}s"


@dataclass
class Summary:
    """What the stores hold about one collection, as one page. Built by ``summarize``; it reads nothing itself."""

    collection: Collection
    chronology: ch.Chronology
    conflicts: fc.ConflictReport
    files: tuple[FileRow, ...] = ()
    held_back: int = 0                       # files the collection's rule holds back: counted, never named
    has_folder: bool = False                 # the collection has a folder of its own, with an inventory
    fetched: bool = True                     # ... and the folder has been fetched
    matter: tuple[str, ...] = ()             # what the matter is, as the specification's record holds it
    duties: tuple[Any, ...] = ()             # the specification's duties for the matter (``CaseDuty``)

    @property
    def title(self) -> str:
        return self.collection.title

    @property
    def confidential(self) -> bool:
        return self.collection.confidential or self.chronology.confidential or self.conflicts.confidential

    # --- what is missing ---------------------------------------------------------------------------------------------

    def gaps(self) -> tuple[Gap, ...]:
        """What the page could not read or does not hold, by rule, in a fixed order."""
        out: list[Gap] = []
        if self.has_folder and not self.fetched:
            out.append(Gap("not-fetched", "The collection's folder has not been fetched to disk, so its files are "
                                          "known only as far as the index holds them: jason cases --fetch-files."))
        unread = [row for row in self.files if not row.has_text]
        by_why: dict[str, list[FileRow]] = {}
        for row in unread:
            by_why.setdefault(row.why or NOT_READ, []).append(row)
        for why, rows in by_why.items():
            out.append(Gap("no-text", f"No text for {_count(len(rows), 'file')} ({why}): {_names(rows)}.", len(rows)))
        unindexed = [row for row in self.files if row.has_text and not row.indexed]
        if unindexed:
            out.append(Gap("not-indexed", f"Text on disk that the passage index does not hold, so nothing below reads "
                                          f"it, for {_count(len(unindexed), 'file')}: {_names(unindexed)}. Run jason "
                                          f"index --build.", len(unindexed)))
        for row in self.files:
            if row.unread_pages and row.has_text:
                out.append(Gap("pages-unread", f"{row.name}: {row.unread_pages} of {_count(row.pages, 'page')} are "
                                               f"images no reader gave words for (photographs, or scans to read with "
                                               f"a vision model).", row.unread_pages))
        misread = [row for row in self.files if row.may_misread]
        if misread:
            out.append(Gap("may-misread", f"Read at least in part by an OCR engine or a vision model, which may "
                                          f"misread, for {_count(len(misread), 'file')}: {_names(misread)}. Check a "
                                          f"quote against the file.", len(misread)))
        silent = [row for row in self.files if row.indexed and not row.statements]
        if silent:
            out.append(Gap("no-dated-statement", f"No dated statement the readers could read in "
                                                 f"{_count(len(silent), 'file')} with text: {_names(silent)}.",
                           len(silent)))
        if self.chronology.partial:
            out.append(Gap("no-year", f"Not placed: about {_count(self.chronology.partial, 'mention')} of a month and "
                                      f"a day with no year (a spoken or a short date).", self.chronology.partial))
        if self.held_back:
            out.append(Gap("held-back", f"Held back by the collection's rule: {_count(self.held_back, 'file')}, not "
                                        f"fetched, not read, and not named here. No count above includes them.",
                           self.held_back))
        if not self.conflicts.readings:
            out.append(Gap("no-stored-reading", "No document reader's stored reading belongs to the collection's "
                                                "files, so the stored-field rule compared nothing. Only the text rules "
                                                "looked for conflicts."))
        elif self.conflicts.not_compared:
            out.append(Gap("kinds-not-compared", "Stored readings of these kinds have no rule row and were not "
                                                 "compared: " + ", ".join(self.conflicts.not_compared) + ".",
                           len(self.conflicts.not_compared)))
        return tuple(out)

    # --- the open questions ------------------------------------------------------------------------------------------

    def questions(self) -> tuple[str, ...]:
        """The facts the stores leave undetermined, each as a question for a person. jason answers none."""
        events = self.chronology.events
        out: list[str] = []
        for duty in self.duties:
            if duty.applies and duty.met is None:
                due = f", due {duty.due.isoformat()}" if duty.due else ""
                out.append(f"Was this duty met: {duty.requirement} ({duty.statute}{due})? The specification's record "
                           f"does not show it either way.")
        said = {e.day for e in events} | {e.end for e in events if e.end}
        for entry in self.chronology.recorded:
            if entry.day not in said:
                where = f" (it names its record as: {entry.where})" if entry.where else " (it names no record)"
                out.append(f"The specification records \"{entry.step}\" on {entry.day.isoformat()}{where}. No statement "
                           f"dated that day was read in the collection's files. Which file records it, and can its "
                           f"date be read?")
        for n, conflict in enumerate(self.conflicts.conflicts, 1):
            out.append(f"Which value holds for {conflict.subject}: {conflict.what}? The documents give "
                       f"{len(conflict.sides)} values (conflict {n} below), and jason picks neither.")
        own = {e.place.path for e in events if e.document_day or e.role is ch.DateRole.DOCUMENT}
        own |= {place.path for e in events if e.role is ch.DateRole.DOCUMENT for place in e.also}
        for row in self.files:
            if not row.indexed or row.path in own:
                continue
            hints = []
            for role, said_how in ((ch.DateRole.HEADING, "a line at its head carries"), (ch.DateRole.NAME, "its name prints")):
                written = next((e.written for e in events if e.place.path == row.path and e.role is role), "")
                if written:
                    hints.append(f"{said_how} {written}")
            hint = f" ({'; '.join(hints)}, which is not taken for the document's own date)" if hints else ""
            out.append(f"What is the date of {row.name}? No date line or labeled date was read at its head{hint}.")
        for e in events:
            if e.approximate:
                out.append(f"On what day: {e.place.document} gives {e.written} as on or about ({e.place.where}).")
        return tuple(out)

    # --- counts and JSON ---------------------------------------------------------------------------------------------

    def how_read(self) -> dict[str, int]:
        """The files by how each was read. A file with no text is counted under ``NOT_READ``."""
        out: dict[str, int] = {}
        for row in self.files:
            how = row.how.split(" (", 1)[0] if row.has_text else NOT_READ
            out[how] = out.get(how, 0) + 1
        return dict(sorted(out.items()))

    def counts(self) -> dict[str, Any]:
        chronology = self.chronology.counts()
        return {"files": len(self.files), "filesWithText": sum(1 for r in self.files if r.has_text),
                "filesIndexed": sum(1 for r in self.files if r.indexed), "filesByHowRead": self.how_read(),
                "heldBack": self.held_back, "pagesUnread": sum(r.unread_pages for r in self.files),
                "datedStatements": chronology["events"], "statementsByRole": chronology["byRole"],
                "nearCopiesFolded": chronology["folded"], "recordedEvents": chronology["recorded"],
                "duties": len(self.duties), "conflicts": len(self.conflicts.conflicts),
                "missing": len(self.gaps()), "openQuestions": len(self.questions())}

    def as_dict(self) -> dict[str, Any]:
        c = self.collection
        return {"key": c.key, "title": c.title, "kind": c.kind.value, "generatedBy": "jason (rule-based; no model)",
                "standing": "a summary, not the record", "confidential": self.confidential,
                "scope": ch.describe_scope(c.scope), "label": c.label, "counts": self.counts(),
                "context": {"title": c.context_title, "lines": list(c.context)},
                "files": [row.as_dict() for row in self.files], "heldBack": self.held_back,
                "missing": [gap.as_dict() for gap in self.gaps()], "openQuestions": list(self.questions()),
                "conflicts": self.conflicts.as_dict(), "chronology": self.chronology.as_dict(),
                "caveats": [*CAVEATS, *ch.CAVEATS, *fc.CAVEATS]}

    # --- the page ----------------------------------------------------------------------------------------------------

    def _context_section(self) -> list[str]:
        c = self.collection
        if not c.context:
            return []
        out = [f"## {context_heading(c)}", ""]
        if not self.matter:
            return [*out, "These lines were given with the collection. None is a quote from a file.", "",
                    *[f"- {line}" for line in c.context], ""]
        out += ["These lines are the specification's record of the matter: the profile's entries, confirmed by a "
                "person. None is a quote from a file of the collection, and none is merged with what the documents "
                "say below.", "", *[f"- {line}" for line in self.matter], ""]
        out += [f"### {RECORDED_EVENTS}", ""]
        out += [f"- {e.day.isoformat()}: {e.step}" + (f" (recorded in: {e.where})" if e.where else "")
                for e in self.chronology.recorded] or ["The specification records no event for the matter."]
        out += ["", f"### {RECORDED_DUTIES}", ""]
        out += [f"- {duty_line(duty)}" for duty in self.duties] or ["The specification records no duty for the matter."]
        return [*out, ""]

    def _files_section(self) -> list[str]:
        out = [f"## {FILES}", ""]
        if not self.files:
            out += ["The passage index holds no file under the collection's scope.", ""]
        else:
            out += ["| File | Kind | Standing | How its words were read | Pages unread | Dated statements |",
                    "|---|---|---|---|---|---|"]
            for row in self.files:
                standing = row.standing.value if row.standing else "not in the index"
                pages = f"{row.unread_pages} of {row.pages}" if row.unread_pages else ("0" if row.pages else "")
                cells = (row.name, row.kind.replace("_", " "), standing, row.how, pages,
                         str(row.statements) if row.indexed else "")
                out.append("| " + " | ".join(cell.replace("|", "\\|") for cell in cells) + " |")
            out.append("")
        if self.has_folder:
            out += [f"Held back by the collection's rule: {_count(self.held_back, 'file')}, not fetched or read. None "
                    f"is named on this page.", ""]
        return out

    def _chronology_section(self) -> list[str]:
        events = self.chronology.events
        out = [f"## {CHRONOLOGY}", "",
               "Each line is one document's statement: what kind of date it is, the file and the passage it sits in, "
               "then the document's words. None is a finding that the event happened. The specification's own "
               "entries are in their section above and are not merged here.", ""]
        groups = ((OWN_DATES, (ch.DateRole.DOCUMENT,),
                   "Read from a date line or a labeled line at the document's head, by rule."),
                  (OTHER_DATES, (ch.DateRole.HEADING, ch.DateRole.EMBEDDED, ch.DateRole.NAME),
                   "None of these is taken for the document's own date."),
                  (ABOUT_DATES, (ch.DateRole.ABOUT,), "In date order. A range is listed at its first day."))
        for heading, roles, note in groups:
            out += [f"### {heading}", "", note, ""]
            found = [e for e in events if e.role in roles]
            if not found:
                out += ["None was read.", ""]
            for e in found:
                out += ch.event_lines(e, dated=True)
        return out

    def markdown(self, today: date | None = None) -> str:
        """The generated page, whole. The same stores give the same page, apart from the line that carries ``today``."""
        today = today or date.today()
        c = self.collection
        counts = self.counts()
        gaps, questions = self.gaps(), self.questions()
        extra = [f"Collection: {c.key} ({c.kind.value}). Its material is {c.label}.",
                 f"Found: {counts['filesIndexed']} files in the index, {counts['files'] - counts['filesWithText']} with "
                 f"no text, {self.held_back} held back; {counts['datedStatements']} dated statements; "
                 f"{counts['conflicts']} conflicts of fact; {len(gaps)} lines of what is missing or unread; "
                 f"{len(questions)} open questions.",
                 f"Rebuilt, never edited: jason collection {c.key} --write writes this page again whole from the "
                 f"stores."]
        out = ch.page_header(f"Summary: {c.title}", today=today, scope=c.scope, files=self.chronology.files,
                             what="Every statement names the file and the passage it rests on. Nothing here finds "
                                  "that an event happened: it says only that a document says so.",
                             extra=extra, confidential=self.confidential)
        out += [f"## {WHAT}", "",
                f"{c.title} is a collection of documents reviewed together ({c.kind.value}; key {c.key}). Its material "
                f"is {c.label}.", "",
                f"The sections below give the collection's files and how each was read, what is missing or unread, "
                f"the open questions, the conflicts of fact, and the chronology of what the documents say.", ""]
        out += self._context_section()
        out += self._files_section()
        out += [f"## {MISSING}", ""]
        out += [f"- {gap.text}" for gap in gaps] or ["Nothing is recorded as missing or unread. That is not a finding "
                                                     "that the collection is complete."]
        out += ["", f"## {QUESTIONS}", "",
                "Facts the stores leave undetermined, found by rule. Each is a question for a person, and jason "
                "answers none.", ""]
        out += [f"- {question}" for question in questions] or ["None was found by rule."]
        out += ["", f"## {CONFLICTS}", "",
                "Where two documents give different values for what a rule took to be the same fact. Every side is "
                "kept with its source, jason picks neither, and the order of the sides means nothing.", ""]
        if not self.conflicts.conflicts:
            out += ["No conflict was found by the rules. That is not a finding that the documents agree.", ""]
        for n, conflict in enumerate(self.conflicts.conflicts, 1):
            out += fc.conflict_lines(n, conflict, level="###")
        out += self._chronology_section()
        out += ["## Caveats", "", *[f"- {caveat}" for caveat in (*CAVEATS, *ch.CAVEATS, *fc.CAVEATS)], ""]
        return "\n".join(out)


def summarize(community: Any, data_dir: Path | str, collection: Collection, *, today: date | None = None,
              readings: Sequence[dict[str, Any]] | None = None) -> Summary:
    """The summary of one collection, from the stores: the passage index under the collection's scope, the
    specification's record of the matter, the collection's folder (a legal case's manifest and extracts), and the
    document readers' stored readings (``readings`` replaces them). Reads only. Raises ``FileNotFoundError`` when
    there is no passage index."""
    data_dir = Path(data_dir)
    case = case_of(community, collection)
    chronology = ch.chronology(data_dir, collection.scope, collection.title,
                               recorded=case.events if case is not None else (),
                               recorded_confidential=collection.confidential, today=today)
    conflicts = fc.fact_conflicts(data_dir, collection.scope, collection.title, readings=readings, today=today)
    inventory = None
    if case is not None and collection.folder:
        from jason.tasks.case_files import inventory as case_inventory

        inventory = case_inventory(data_dir, case)
    return Summary(collection, chronology, conflicts, file_rows(data_dir, collection, chronology.files, inventory),
                   held_back=inventory.held_back if inventory is not None else 0, has_folder=inventory is not None,
                   fetched=inventory.fetched if inventory is not None else True,
                   matter=case_matter(case) if case is not None else (),
                   duties=tuple(case.duties) if case is not None else ())


def summary_path(data_dir: Path | str, collection: Collection) -> Path:
    return Path(data_dir) / collection.pages_folder / SUMMARY_PAGE


def write(data_dir: Path | str, summary: Summary, *, today: date | None = None) -> Path:
    """Save the summary page (``data/collections/<key>/summary.md``) under the store lock, whole."""
    return ch.write_page(data_dir, ch.slug_of(summary.collection.key), SUMMARY_PAGE, summary.markdown(today))


# --- the index --------------------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class PagesSource:
    """One collection's generated pages for the passage index (``passage_index.build``): every Markdown page in its
    folder, in the collection's own catalog, with the standing ``page``, generated, and as confidential as the
    collection. A hit on one is a summary, never the record."""

    collection: Collection

    @property
    def catalog(self) -> str:
        return self.collection.page_catalog

    @property
    def catalogs(self) -> tuple[str, ...]:
        return (self.catalog,)

    @property
    def folder(self) -> str:
        return self.collection.pages_folder

    def entries(self, data_dir: Path) -> Iterable[IndexFile]:
        root = Path(data_dir) / self.folder
        if not root.is_dir():
            return
        context = f"{SUMMARY_LABEL} ({self.collection.title})"
        for path in sorted(root.glob("*.md")):
            yield IndexFile(path, self.catalog, Standing.PAGE, kind="", confidential=self.collection.confidential,
                            generated=True, context=context)


def index_sources(collections: Iterable[Collection]) -> tuple[PagesSource, ...]:
    """One ``PagesSource`` per collection: its generated pages, in its own catalog."""
    return tuple(PagesSource(found) for found in collections)


__all__ = ["CAVEATS", "FileRow", "Gap", "PagesSource", "Summary", "case_of", "file_rows", "index_sources", "summarize",
           "summary_path", "write"]
