"""Which inspection periods have a record on file: the completeness lens over the life safety records.

``jason inspections`` asks, for each of the profile's life safety systems and each obligation that applies to it
(``jason.community.life_safety.applicable``), which periods have a report on file and which do not. It is the
"Completeness" lens of docs/ingestion-and-review.md for one collection: which documents should the collection hold
that it does not?

**What counts as on file.** Two kinds of record, and nothing else:

- an inspection-report reading (``data/documents/readings.json``, kind ``inspection_report``), placed by the reading's
  own fields: ``system``, ``building`` (or ``buildings``), and ``inspection_date``;
- a completion a person recorded (``data/schedule/done.jsonl``, ``jason schedule --done``), where its assignment
  covers one obligation and that obligation applies to one system.

A payment is not a record here (``jason deadlines`` shows payments), and a file's name places nothing. A reading that
lacks a field is listed as **unplaced** with the field it lacks, never guessed into a period. A report jason has on
disk but no reader has read (a library file with no reading, a vendor's report in the filing log,
``data/drive/vendor-files.jsonl``) is listed as **not read**.

**Periods.** One scheduler: the frequency is the obligation row's (``Obligation.months``), the date arithmetic is
``jason.tasks.deadlines.add_months``, and each obligation's own calendar row (``deadlines.obligation_rows``: next due,
standing) is shown beside its periods. A row with a first due date is counted in periods that end on it and on each
date after it by the frequency. A row without one is counted from the earliest day the calendar would count from: the
earliest record on file, the date the row gives for its last record, or the earliest payment the calendar counts
(``firstDone``). That day opens the count, and each period after it ends one interval later, the way the calendar
counts the next due date from the last record. A payment only opens the count; it never covers a period. The period
still running closes the list as "not yet due". A row with nothing to count from has no period to list, and says so.
A report made late falls in the next period.

**Which obligation a report shows.** Where one obligation with a frequency applies to the system, a report of that
system is its record. Where several apply, the reading must say which: ``interval_months`` (3 for a quarterly
inspection, 12 for an annual one). A reading that does not is listed under the system as not assigned.

**Deficiencies.** A report that reports deficiencies is shown with its count. A later reading of the same system and
building whose result is passed with none open is named beside it, as that report's result and not as a record of the
repair; otherwise "no correction on file".

**The record-keeping rule** is recited from the authorities shelf (``recite``): the words of each ``RecordRule`` row
(``jason.community.fire_protection.RECORD_RULES``) as the shelf's copy of the publication prints them, with the
citation. A provision the shelf does not print is cited and said to be missing; it is never quoted from memory.

``completeness`` is pure. ``review`` reads the stores and calls it; ``write`` saves the page. Nothing here calls an
outside service.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, replace
from datetime import date, timedelta
from enum import Enum
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from jason.community.applicability import Facts, SystemKind, partition, profile_facts
from jason.community.fire_protection import RECORD_RULES, RecordRule
from jason.community.life_safety import (
    SUBJECT_FACTS,
    Finding,
    LifeSafetySystem,
    SystemApplicability,
    applicable,
    row_name,
    system_facts,
)
from jason.tasks.deadlines import add_months

REPORT_KIND = "inspection_report"
PAGE = Path("reports") / "life-safety-records.md"
LOCK_KEY = "life-safety-records"

CAVEATS = (
    "Generated by jason from the documents listed. It is a summary, not the record: read the report itself before "
    "relying on a line.",
    "\"Not on file\" means no reading and no completion on jason's disk falls in the period. A record kept somewhere "
    "jason does not read is not seen, and \"not on file\" never means \"not done\".",
    "A report is placed by its reading's own fields (system, building, inspection date). One that lacks a field is "
    "listed as unplaced, never guessed into a period.",
    "Periods are counted by the row's frequency from its first due date, or, where the row gives none, from the "
    "earliest day jason deadlines would count from (a record, the row's own date, or a payment). A payment opens the "
    "count and never covers a period. A report made late falls in the next period.",
    "A later report that reads passed with none open is that report's result, not a record of the repair.",
    "A provision is recited from the shelf's copy of the publication, which is not an official restatement; which "
    "system it reaches is the row's condition, a reading.",
)

# The word a reader stores for the system it read, as a general kind. A reader may also store the kind's own word.
SYSTEM_WORDS: dict[str, SystemKind] = {
    "fire alarm": SystemKind.FIRE_ALARM,
    "fire sprinkler": SystemKind.FIRE_SPRINKLER,
    "backflow assembly": SystemKind.BACKFLOW,
    "fire extinguishers": SystemKind.FIRE_EXTINGUISHER,
    "roof": SystemKind.ROOF,
    "elevator": SystemKind.ELEVATOR,
    **{kind.value: kind for kind in SystemKind},
}


class Coverage(Enum):
    COVERED = "covered"
    PARTLY = "partly on file"
    NOT_ON_FILE = "not on file"
    NOT_YET_DUE = "not yet due"


# ---------------------------------------------------------------------------------------------------------------
# The records on file.


def _day(value: Any) -> date | None:
    text = str(value or "")
    try:
        return date.fromisoformat(text[:10]) if len(text) >= 10 else None
    except ValueError:
        return None


def _words(value: Any) -> tuple[str, ...]:
    """A reading's building field as words: one value, or a list of them; empty when the reading names none."""
    if value in (None, "", [], ()):
        return ()
    values = value if isinstance(value, (list, tuple)) else [value]
    return tuple(str(v).strip() for v in values if str(v).strip())


@dataclass(frozen=True)
class Report:
    """One inspection report as its reading gives it. ``kind`` and ``day`` are None, and ``buildings`` empty, where
    the reading does not say; ``model`` is empty where no reader read it."""

    id: str
    name: str
    model: str = ""
    day: date | None = None
    kind: SystemKind | None = None
    system_word: str = ""
    buildings: tuple[str, ...] = ()
    interval_months: int | None = None
    result: str = ""
    deficiencies: int = 0
    open_deficiencies: int = 0
    confidential: bool = False
    has_text: bool = True

    @classmethod
    def of(cls, row: Mapping[str, Any]) -> "Report":
        """A row of the readings store. Only the reading's own fields are read: not the file's name or its period."""
        fields = row.get("fields") or {}
        word = str(fields.get("system") or "").strip().lower()
        interval = fields.get("interval_months")
        return cls(
            id=str(row.get("id") or ""), name=str(row.get("name") or ""), model=str(row.get("model") or ""),
            day=_day(fields.get("inspection_date")), kind=SYSTEM_WORDS.get(word), system_word=word,
            buildings=_words(fields.get("buildings")) or _words(fields.get("building")),
            interval_months=int(interval) if str(interval or "").isdigit() and int(interval) else None,
            result=str(fields.get("result") or ""), deficiencies=len(fields.get("deficiencies") or ()),
            open_deficiencies=int(fields.get("open_deficiencies") or 0),
            confidential=bool(row.get("confidential")), has_text=bool(row.get("hasText", True)))

    @property
    def where(self) -> str:
        return "Drive" if self.id.startswith("drive-") else "library"

    @property
    def label(self) -> str:
        """The document's name, date, and id. A confidential file's name is held back."""
        name = "a confidential document" if self.confidential else (self.name or "an unnamed document")
        when = f"{self.day}, " if self.day else ""
        return f"{name} ({when}{self.where} id {self.id})"

    @property
    def reader(self) -> str:
        return f"the reader {self.model}" if self.model else "no reader"

    @property
    def reports_deficiencies(self) -> bool:
        return bool(self.deficiencies or self.open_deficiencies)

    def as_dict(self) -> dict[str, Any]:
        return {"id": self.id, "name": "" if self.confidential else self.name, "where": self.where,
                "date": self.day.isoformat() if self.day else None, "system": self.kind.value if self.kind else None,
                "buildings": list(self.buildings), "intervalMonths": self.interval_months, "result": self.result,
                "deficiencies": max(self.deficiencies, self.open_deficiencies), "openDeficiencies": self.open_deficiencies,
                "model": self.model, "confidential": self.confidential}


@dataclass(frozen=True)
class Completion:
    """A completion a person recorded for a scheduled assignment (``jason.tasks.schedule.record_done``), with the
    obligations that assignment covers."""

    key: str
    done: date | None
    by: str = ""
    evidence: str = ""
    due: date | None = None
    obligations: tuple[str, ...] = ()

    @property
    def label(self) -> str:
        return (f"recorded done on {self.done} by {self.by or 'a person'} (assignment {self.key})"
                + (f": {self.evidence}" if self.evidence else ""))

    def as_dict(self) -> dict[str, Any]:
        return {"assignment": self.key, "done": self.done.isoformat() if self.done else None, "by": self.by,
                "due": self.due.isoformat() if self.due else None, "evidence": self.evidence}


@dataclass(frozen=True)
class Filing:
    """A report a vendor sent that the filing log shows filed, which no reading covers."""

    vendor: str
    name: str
    sent: str = ""               # the day of the email it came with
    where: str = ""              # the folder it was filed in
    file_id: str = ""
    systems: tuple[str, ...] = ()    # the listed systems the specification names this vendor for

    def as_dict(self) -> dict[str, Any]:
        return {"vendor": self.vendor, "name": self.name, "sent": self.sent, "where": self.where,
                "fileId": self.file_id, "systems": list(self.systems)}


@dataclass(frozen=True)
class Unplaced:
    """A record on file that no period holds, and the field or fact it lacks."""

    label: str
    reason: str
    id: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {"record": self.label, "reason": self.reason, "id": self.id}


@dataclass(frozen=True)
class Placed:
    """A report placed on a system: the buildings of the system it covers (one empty word for a system the
    specification does not divide by building), and, for one that reports deficiencies, the later report on file
    that reads passed with none open."""

    report: Report
    system: LifeSafetySystem
    slots: tuple[str, ...]
    correction: Report | None = None

    def deficiency_text(self) -> str:
        r = self.report
        if not r.reports_deficiencies:
            return ""
        n = max(r.deficiencies, r.open_deficiencies)
        text = f"{n} deficienc{'y' if n == 1 else 'ies'} reported" + (f", {r.open_deficiencies} open" if r.open_deficiencies else "")
        if self.correction is not None:
            return f"{text}; a later report on file reads passed with none open: {self.correction.label}"
        return f"{text}; no correction on file"

    def as_dict(self) -> dict[str, Any]:
        row = {**self.report.as_dict(), "placedOn": [s for s in self.slots if s]}
        if self.report.reports_deficiencies:
            row["correction"] = self.correction.as_dict() if self.correction else None
            row["correctionNote"] = ("a later report reads passed with none open; its result, not a record of the repair"
                                     if self.correction else "no correction on file")
        return row


# ---------------------------------------------------------------------------------------------------------------
# Placing a record: which system, which buildings, which obligation.


def slots_of(system: LifeSafetySystem) -> tuple[str, ...]:
    """The buildings a system serves, as words; one empty word where the specification does not divide it."""
    return tuple(str(getattr(s, "value", s)) for s in system.serves) or ("",)


def place(report: Report, systems: Sequence[LifeSafetySystem]) -> tuple[LifeSafetySystem | None, tuple[str, ...], str]:
    """The system and buildings a report belongs to by its reading's own fields, or the reason it has none."""
    if not report.model:
        return None, (), ("not read: no text on disk" if not report.has_text
                          else "not read: no reader has read it (jason models)")
    if report.kind is None:
        said = f" (it says \"{report.system_word}\")" if report.system_word else ""
        return None, (), f"{report.reader} does not say which system{said}: the field system"
    if report.day is None:
        return None, (), f"{report.reader} gives no inspection date: the field inspection_date"
    same = [s for s in systems if s.kind is report.kind]
    if not same:
        return None, (), f"the reading names {_a(report.kind.label)}; the specification lists no such system"
    whole = [s for s in same if not s.serves]
    if report.buildings:
        holders = [s for s in same if set(report.buildings) <= set(slots_of(s))]
        if len(holders) == 1:
            return holders[0], report.buildings, ""
        if len(holders) > 1:
            return None, (), f"more than one listed {report.kind.label} serves building {', '.join(report.buildings)}"
        if len(same) == 1 and whole:
            return same[0], ("",), ""                # the only such system, which the specification does not divide
        return None, (), (f"the reading says building {', '.join(report.buildings)}, which no one listed "
                          f"{report.kind.label} serves")
    if len(same) == 1 and whole:
        return same[0], ("",), ""
    return None, (), f"{report.reader} does not say which building: the field building"


def _a(label: str) -> str:
    return ("an " if label[:1].lower() in "aeiou" else "a ") + label


def months_of(row: Any) -> int:
    """A row's interval in months: its own, or twelve for a fixed yearly deadline; 0 for a row with no frequency."""
    return int(getattr(row, "months", 0) or 0) or (12 if getattr(row, "fixed", False) else 0)


def obligation_for(report: Report, rows: Sequence[Any]) -> tuple[Any | None, str]:
    """Which of a system's applicable obligations a report is the record of, or why none can be named."""
    timed = [r for r in rows if months_of(r)]
    if not timed:
        return None, "no obligation with a frequency applies to the system"
    if report.interval_months:
        match = [r for r in timed if months_of(r) == report.interval_months]
        if len(match) == 1:
            return match[0], ""
        if not match:
            return None, f"the reading says every {report.interval_months} months, and no obligation of the system runs so"
        return None, (f"{len(match)} obligations of the system run every {report.interval_months} months, and the "
                      "reading does not say which")
    if len(timed) == 1:
        return timed[0], ""
    return None, (f"{len(timed)} obligations apply to the system, and {report.reader} does not say which inspection "
                  "it records: the field interval_months")


# ---------------------------------------------------------------------------------------------------------------
# Periods.


@dataclass(frozen=True)
class Period:
    """One period of an obligation for a system. ``start`` is its first day, None for the day the count opens on.
    ``missing`` are the buildings with nothing on file in it (empty for a system not divided by building)."""

    start: date | None
    end: date
    status: Coverage
    reports: tuple[Placed, ...] = ()
    completions: tuple[Completion, ...] = ()
    missing: tuple[str, ...] = ()
    note: str = ""

    @property
    def label(self) -> str:
        return f"on {self.end}" if self.start is None else f"{self.start} to {self.end}"

    def as_dict(self) -> dict[str, Any]:
        return {"start": self.start.isoformat() if self.start else None, "end": self.end.isoformat(),
                "status": self.status.value, "reports": [p.as_dict() for p in self.reports],
                "completions": [c.as_dict() for c in self.completions], "missing": list(self.missing), "note": self.note}


@dataclass(frozen=True)
class ObligationRecords:
    """One obligation that applies to a system, and its periods. ``counted_from`` is None, and ``periods`` empty,
    where the row gives no first due date and no record is on file to count from. ``earlier`` are records dated
    before the first period. ``calendar`` is the obligation's own row of ``jason deadlines``."""

    row: Any
    finding: Finding
    counted_from: date | None = None
    counted_how: str = ""
    periods: tuple[Period, ...] = ()
    earlier: tuple[Placed, ...] = ()
    calendar: Mapping[str, Any] | None = None

    def counts(self) -> dict[str, int]:
        out = {c.value: 0 for c in Coverage}
        for p in self.periods:
            out[p.status.value] += 1
        return out

    def as_dict(self) -> dict[str, Any]:
        cal = self.calendar or {}
        return {"obligation": row_name(self.row), "authority": getattr(self.row, "authority", ""),
                "cadence": cadence_of(self.row), "countedFrom": self.counted_from.isoformat() if self.counted_from else None,
                "countedHow": self.counted_how, "periods": [p.as_dict() for p in self.periods], "counts": self.counts(),
                "earlier": [p.as_dict() for p in self.earlier],
                "calendar": {k: cal.get(k) for k in ("next", "standing", "lastDone", "daysLeft")} if cal else None}


def cadence_of(row: Any) -> str:
    if getattr(row, "fixed", False):
        return f"yearly by {row.deadline(2000):%B} {row.day}"
    return row.cadence() if months_of(row) else "no frequency"


def _spans(row: Any, days: Sequence[date], as_of: date, counted: date | None = None
           ) -> tuple[date | None, str, list[tuple[date | None, date]]]:
    """The periods of a row as (the day before the first day, or None for the opening day; the last day), with the day
    counting starts on and how it was chosen. ``days`` are the records on file and ``counted`` the earliest day the
    calendar's own evidence gives (a payment). No periods where there is nothing to count from."""
    months = months_of(row)
    first_due = getattr(row, "first_due", None)
    done_on = getattr(row, "done_on", None)
    known = sorted({*days, *([done_on] if done_on else []), *([counted] if counted else [])})
    if not months:
        return None, "The row gives no frequency, so it has no periods.", []
    opening = False
    if getattr(row, "fixed", False):
        base = first_due or (known[0] if known else None)
        if base is None:
            return None, "No record is on file to count from, so no period can be listed.", []
        anchor = row.deadline(base.year) if row.deadline(base.year) >= base else row.deadline(base.year + 1)
        how = "the row's yearly deadline"
    elif first_due is not None:
        anchor, how = first_due, "the row's first due date"
    elif known:
        anchor, opening = known[0], True
        how = ("the earliest record on file" if anchor in days
               else "the date the row gives for its last record" if done_on == anchor
               else "the earliest payment jason deadlines counts for it (a payment opens the count; it is not a record)")
    else:
        return None, ("The row gives no first due date and no record is on file to count from, so no period can be "
                      "listed."), []
    spans: list[tuple[date | None, date]] = []
    k = 0
    while True:
        end = add_months(anchor, k * months)
        spans.append((None if opening and k == 0 else add_months(anchor, (k - 1) * months), end))
        if end > as_of:
            break
        k += 1
    return anchor, how, spans


def _records(row: Any, finding: Finding, placed: Sequence[Placed], done: Sequence[Completion], as_of: date,
             calendar: Mapping[str, Any] | None) -> ObligationRecords:
    system = finding.system
    slots = slots_of(system) if system else ("",)
    days = [p.report.day for p in placed if p.report.day] + [c.done for c in done if c.done]
    counted = _day((calendar or {}).get("firstDone"))
    anchor, how, spans = _spans(row, days, as_of, counted)
    done_on = getattr(row, "done_on", None)
    periods: list[Period] = []
    for k, (before, end) in enumerate(spans):
        inside = (lambda d: d == end) if before is None else (lambda d: before < d <= end)  # noqa: E731
        reports = tuple(p for p in placed if p.report.day and inside(p.report.day))
        completions = tuple(c for c in done if c.done and inside(c.done))
        opening = before is None
        covered = {s for p in reports for s in p.slots}
        missing = () if completions or opening else tuple(s for s in slots if s not in covered)
        if reports or completions:
            status = Coverage.COVERED if not missing else Coverage.NOT_YET_DUE if end > as_of else Coverage.PARTLY
        else:
            status = Coverage.NOT_YET_DUE if end > as_of else Coverage.NOT_ON_FILE
            missing = ()
        note = ""
        if done_on and inside(done_on) and not any(p.report.day == done_on for p in reports):
            note = f"The row dates a record on {done_on}; no reading of it is on file."
        elif opening and not reports and not completions:
            note = "jason deadlines counts a payment on this day; no report for it is on file."
        periods.append(Period(None if opening else before + timedelta(days=1), end, status, reports, completions,
                              tuple(s for s in missing if s), note))
    first_day = periods[0].start or periods[0].end if periods else None
    earlier = tuple(p for p in placed if first_day and p.report.day and p.report.day < first_day)
    return ObligationRecords(row, finding, anchor, how, tuple(periods), earlier, calendar)


# ---------------------------------------------------------------------------------------------------------------
# The record-keeping rule, recited.


@dataclass(frozen=True)
class Recital:
    """A record-keeping provision's words from the shelf, or why they are not there. ``reaches`` are the listed
    systems the row's condition holds for; ``asks`` the questions where it cannot be decided."""

    rule: RecordRule
    found: bool = False
    words: str = ""
    source: str = ""
    reason: str = ""
    reaches: tuple[str, ...] = ()
    asks: tuple[str, ...] = ()

    def as_dict(self) -> dict[str, Any]:
        return {"key": self.rule.key, "citation": self.rule.citation, "about": self.rule.about, "found": self.found,
                "words": self.words, "source": self.source, "reason": self.reason, "reaches": list(self.reaches),
                "condition": self.rule.applies.describe(), "questions": list(self.asks)}


_PAGE_MARK = re.compile(r"<<PAGE \d+>>\s*$")
# A section's first line: "§904.1. Inspection Requirements." or "904.2. Testing ...". A list item ("1. ...") is not one.
_HEADING = re.compile(r"(?:§\s*\d+|\d{2,})(?:\.\d+)*\.\s+\S")


def _shelf_lines(text: str) -> list[str]:
    """A publication's text without its page marks, and without the page number printed just before each."""
    lines = text.splitlines()
    drop: set[int] = set()
    for i, line in enumerate(lines):
        if not _PAGE_MARK.match(line.strip()):
            continue
        drop.add(i)
        j = i - 1
        while j >= 0 and not lines[j].strip():
            j -= 1
        if j >= 0 and re.fullmatch(r"\d{1,4}", lines[j].strip()):
            drop.add(j)
    return [line for i, line in enumerate(lines) if i not in drop]


def recite(data_dir: Path | str, rule: RecordRule, *, publications: Iterable[Any] | None = None) -> Recital:
    """The provision's words as the shelf's copy of its publication prints them, found by the row's locator: the
    section's first line, the provision's first line inside it, and the first line after it. A miss names why, and
    nothing is quoted."""
    from jason.tasks.export_authorities import PUBLICATIONS_DIR

    if publications is None:
        from jason.community.authorities import PUBLICATIONS as publications
    pub = next((p for p in publications if p.title == rule.publication), None)
    if pub is None:
        return Recital(rule, reason=f"no publication titled \"{rule.publication}\" is listed for the shelf")
    path = Path(data_dir) / PUBLICATIONS_DIR / pub.text_filename
    source = f"{pub.title} ({pub.agency}), {PUBLICATIONS_DIR}/{pub.text_filename}"
    if not path.is_file():
        return Recital(rule, source=source, reason=f"{PUBLICATIONS_DIR}/{pub.text_filename} is not on disk; run "
                                                   "jason export-authorities")
    lines = _shelf_lines(path.read_text(encoding="utf-8", errors="replace"))
    section, start, end = (re.compile(p) for p in (rule.section, rule.start, rule.end))
    seen = False
    for i, line in enumerate(lines):
        if not section.match(line.strip()):
            continue
        seen = True
        for j in range(i + 1, len(lines)):
            here = lines[j].strip()
            if _HEADING.match(here) or section.match(here):
                break                                   # the next section: the provision is not in this one
            if not start.match(here):
                continue
            body = [here]
            for nxt in lines[j + 1:]:
                nxt = nxt.strip()
                if end.match(nxt) or _HEADING.match(nxt):
                    break
                body.append(nxt)
            return Recital(rule, True, " ".join(" ".join(body).split()), source)
    reason = ("the shelf's copy prints the section without this provision" if seen
              else "the shelf's copy does not print the section")
    return Recital(rule, source=source, reason=reason)


# ---------------------------------------------------------------------------------------------------------------
# The whole result.


@dataclass(frozen=True)
class SystemRecords:
    """One system: the obligations that apply with their periods, the reports of it no obligation could be named for,
    the obligations that do not apply with the fact that decided each, and the undetermined ones as questions."""

    system: LifeSafetySystem
    obligations: tuple[ObligationRecords, ...] = ()
    unassigned: tuple[tuple[Placed, str], ...] = ()
    does_not_apply: tuple[Finding, ...] = ()
    undetermined: tuple[Finding, ...] = ()
    not_read: tuple[Filing, ...] = ()

    def as_dict(self) -> dict[str, Any]:
        return {"system": self.system.as_dict(), "obligations": [o.as_dict() for o in self.obligations],
                "unassigned": [{**p.as_dict(), "reason": why} for p, why in self.unassigned],
                "doesNotApply": [f.as_dict() for f in self.does_not_apply],
                "undetermined": [f.as_dict() for f in self.undetermined],
                "notRead": [f.as_dict() for f in self.not_read]}


@dataclass(frozen=True)
class Records:
    as_of: date
    systems: tuple[SystemRecords, ...] = ()
    unplaced: tuple[Unplaced, ...] = ()
    recitals: tuple[Recital, ...] = ()
    questions: tuple[str, ...] = ()
    other_filings: int = 0               # reports in the filing log from vendors no listed system names
    listed: bool = True                  # False where the specification lists no systems
    community: str = ""
    sources: tuple[str, ...] = field(default_factory=tuple)

    def of(self, key: str) -> "Records | None":
        """The same result for one system; None when no system has the key."""
        one = tuple(s for s in self.systems if s.system.key == key)
        if not one:
            return None
        return replace(self, systems=one)

    def summary(self) -> list[dict[str, Any]]:
        """Per system and obligation, how many periods stand covered, partly on file, not on file, and not yet due;
        ``note`` says why where no period could be listed."""
        return [{"system": s.system.key, "obligation": row_name(o.row), "cadence": cadence_of(o.row),
                 "periods": len(o.periods), **o.counts(), "note": "" if o.periods else o.counted_how}
                for s in self.systems for o in s.obligations]

    def as_dict(self) -> dict[str, Any]:
        return {"community": self.community, "asOf": self.as_of.isoformat(), "systems": [s.as_dict() for s in self.systems],
                "summary": self.summary(), "unplaced": [u.as_dict() for u in self.unplaced],
                "recordKeeping": [r.as_dict() for r in self.recitals], "questions": list(self.questions),
                "otherFilings": self.other_filings, "sources": list(self.sources), "caveats": list(CAVEATS)}


def _corrected(placed: Sequence[Placed]) -> list[Placed]:
    """Each placed report with, where it reports deficiencies, the earliest later report of the same system and
    buildings that reads passed with none open."""
    out = []
    for p in placed:
        later = None
        if p.report.reports_deficiencies:
            found = [q.report for q in placed if q.system is p.system and q.report.day and p.report.day
                     and q.report.day > p.report.day and set(p.slots) <= set(q.slots)
                     and q.report.result == "passed" and not q.report.reports_deficiencies]
            later = min(found, key=lambda r: r.day) if found else None
        out.append(Placed(p.report, p.system, p.slots, later))
    return out


def completeness(community: Any, readings: Iterable[Mapping[str, Any]], *, as_of: date,
                 completions: Iterable[Completion] = (), filings: Iterable[Filing] = (),
                 calendar: Iterable[Mapping[str, Any]] = (), recitals: Iterable[Recital] = (),
                 applicability: SystemApplicability | None = None) -> Records:
    """For each of the community's systems and each obligation that applies to it, the periods and what is on file
    in each; with what could not be placed and why, what does not apply and the fact that decided it, and what is
    undetermined as a question.

    ``readings`` are rows of the readings store (other kinds are passed over). ``completions`` are a person's records
    with the obligations each one's assignment covers. ``filings`` are the filing log's reports no reading covers.
    ``calendar`` are the obligations' rows of ``jason deadlines``. ``recitals`` are the record-keeping provisions as
    ``recite`` found them. Pure: it reads nothing.
    """
    result = applicability or applicable(community, as_of=as_of)
    systems = result.systems
    calendar_by = {str(r.get("name")): r for r in calendar}
    unplaced: list[Unplaced] = []

    placed: list[Placed] = []
    for row in readings:
        if row.get("kind") not in (None, REPORT_KIND):
            continue
        report = Report.of(row)
        system, slots, why = place(report, systems)
        if system is None:
            unplaced.append(Unplaced(report.label, why, report.id))
        else:
            placed.append(Placed(report, system, slots))
    placed = _corrected(placed)

    # A completion is a record of one obligation for one system, or it is unplaced.
    applying: dict[str, list[Finding]] = {}
    for f in result.applies:
        if f.system is not None:
            applying.setdefault(row_name(f.row), []).append(f)
    done: dict[tuple[str, str], list[Completion]] = {}
    for c in completions:
        named = [n for n in c.obligations if n in applying]
        if not named:
            continue                                     # not a record of any system's obligation
        if len(c.obligations) != 1:
            unplaced.append(Unplaced(c.label, f"its assignment covers {len(c.obligations)} obligations, and the record "
                                              "does not say which", c.key))
        elif len(applying[named[0]]) != 1:
            unplaced.append(Unplaced(c.label, f"the obligation applies to {len(applying[named[0]])} systems, and the "
                                              "record does not say which", c.key))
        elif c.done is None:
            unplaced.append(Unplaced(c.label, "the record gives no date it was done", c.key))
        else:
            done.setdefault((applying[named[0]][0].system.key, named[0]), []).append(c)

    by_vendor: dict[str, list[Filing]] = {}
    other = 0
    for filing in filings:
        keys = tuple(s.key for s in systems if filing.vendor and filing.vendor.lower() in
                     (s.servicer.lower(), s.monitor.lower()))
        if not keys:
            other += 1
        for key in keys:
            by_vendor.setdefault(key, []).append(Filing(filing.vendor, filing.name, filing.sent, filing.where,
                                                        filing.file_id, keys))

    out: list[SystemRecords] = []
    for system in systems:
        part = result.of(system)
        rows = [f.row for f in part.applies]
        mine = [p for p in placed if p.system is system]
        assigned: dict[int, list[Placed]] = {}
        unassigned: list[tuple[Placed, str]] = []
        for p in mine:
            row, why = obligation_for(p.report, rows)
            if row is None:
                unassigned.append((p, why))
            else:
                assigned.setdefault(id(row), []).append(p)
        obligations = tuple(
            _records(f.row, f, sorted(assigned.get(id(f.row), []), key=lambda p: (p.report.day, p.slots)),
                     done.get((system.key, row_name(f.row)), []), as_of, calendar_by.get(row_name(f.row)))
            for f in part.applies)
        out.append(SystemRecords(system, obligations, tuple(unassigned), part.does_not_apply, part.undetermined,
                                 tuple(by_vendor.get(system.key, ()))))

    base = Facts.build(profile=profile_facts(community), as_of=as_of)
    reached: list[Recital] = []
    for recital in recitals:
        reaches, asks = [], []
        for system in systems:
            parts = partition([recital.rule], base.merge(system_facts(system)))
            if parts.applies:
                reaches.append(system.name)
            for _, verdict in parts.undetermined:
                asks.append(Finding(recital.rule, system, verdict).question())
        reached.append(Recital(recital.rule, recital.found, recital.words, recital.source, recital.reason,
                               tuple(reaches), tuple(asks)))

    # A system's open answers, and (where the specification lists no systems) the question of which it has.
    asked = [f for f in result.undetermined if f.system is not None or SUBJECT_FACTS.intersection(f.verdict.missing)]
    questions = tuple(dict.fromkeys(f.question() for f in asked))
    return Records(as_of, tuple(out), tuple(unplaced), tuple(reached), questions, other, bool(systems),
                   str(getattr(community, "name", "") or ""))


# ---------------------------------------------------------------------------------------------------------------
# The stores.


def _completions(data_dir: Path, community: Any) -> list[Completion]:
    from jason.community.schedule import assignments
    from jason.tasks.schedule import completions

    rows = completions(data_dir)
    if not rows:
        return []
    covers = {a.key: tuple(c.split(":", 1)[1] for c in a.covers if c.startswith("obligation:"))
              for a in assignments(community)}
    return [Completion(str(r.get("key") or ""), _day(r.get("done")), str(r.get("by") or ""), str(r.get("evidence") or ""),
                       _day(r.get("due")), covers.get(str(r.get("key") or ""), ())) for r in rows]


def _library(data_dir: Path) -> tuple[dict[str, Any], ...]:
    from jason.tasks.library import load

    try:
        return load(data_dir)
    except Exception:  # noqa: BLE001 - an unreadable library is no library; the page says which stores it read
        return ()


def _filings(data_dir: Path, read_ids: set[str], read_shas: set[str]) -> list[Filing]:
    """The filing log's inspection reports that no reading covers: not the Drive file's own reading, and not a
    library copy with the same bytes."""
    from jason.tasks.vendor_files import LOG

    path = Path(data_dir) / "drive" / LOG
    if not path.is_file():
        return []
    out, seen = [], set()
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        file_id = str(row.get("file_id") or "")
        if row.get("kind") != REPORT_KIND or f"drive-{file_id}" in read_ids or row.get("sha256") in read_shas:
            continue
        if (file_id or row.get("sha256")) in seen:
            continue
        seen.add(file_id or row.get("sha256"))
        out.append(Filing(str(row.get("vendor") or ""), str(row.get("name") or ""), str(row.get("at") or "")[:10],
                          str(row.get("where") or ""), file_id))
    return out


def review(data_dir: Path | str, community: Any, *, as_of: date | None = None) -> Records:
    """The completeness of the life safety records from the stores on disk: the readings, the library's inspection
    reports no reading covers, a person's completions, the filing log, the obligations' calendar rows, and the
    record-keeping provisions from the shelf. It reads disk only and writes nothing."""
    from jason.tasks.deadlines import obligation_rows
    from jason.tasks.document_models import load

    data_dir = Path(data_dir)
    day = as_of or date.today()
    readings = [r for r in load(data_dir) if r.get("kind") == REPORT_KIND]
    read_ids = {str(r.get("id")) for r in readings if r.get("model")}
    have = {str(r.get("id")) for r in readings}
    library = _library(data_dir)
    read_shas = {str(r.get("sha256")) for r in library if str(r.get("id")) in read_ids and r.get("sha256")}
    for row in library:                                   # a library report the models never saw
        if row.get("kind") == REPORT_KIND and str(row.get("id")) not in have:
            readings.append({"id": row.get("id"), "name": row.get("name"), "kind": REPORT_KIND, "model": None,
                             "confidential": row.get("confidential"), "hasText": True})
    found = completeness(
        community, readings, as_of=day, completions=_completions(data_dir, community),
        filings=_filings(data_dir, read_ids, read_shas), calendar=obligation_rows(data_dir, community, today=day),
        recitals=[recite(data_dir, rule) for rule in RECORD_RULES])
    sources = ("documents/readings.json (jason models)", "library.db (jason library)", "schedule/done.jsonl",
               "drive/vendor-files.jsonl", "authorities/publications")
    return replace(found, sources=sources)


# ---------------------------------------------------------------------------------------------------------------
# The page.


def _why_groups(findings: Sequence[Finding]) -> list[tuple[str, list[Finding]]]:
    groups: dict[str, list[Finding]] = {}
    for f in findings:
        groups.setdefault(f.why(), []).append(f)
    return list(groups.items())


def _report_line(p: Placed) -> str:
    where = f"building {', '.join(s for s in p.slots if s)}: " if any(p.slots) else ""
    parts = [f"{where}{p.report.label}"]
    if p.report.result:
        parts.append(f"result {p.report.result}")
    if p.deficiency_text():
        parts.append(p.deficiency_text())
    return "; ".join(parts)


def _period_lines(period: Period) -> list[str]:
    out = [f"{period.label}: {period.status.value}"]
    out += [f"  {_report_line(p)}" for p in period.reports]
    out += [f"  {c.label}" for c in period.completions]
    if period.missing:
        out.append(f"  nothing on file for building {', '.join(period.missing)}")
    if period.note:
        out.append(f"  {period.note}")
    return out


def _counts_text(o: ObligationRecords) -> str:
    counts = o.counts()
    return ", ".join(f"{counts[c.value]} {c.value}" for c in Coverage)


def _calendar_text(o: ObligationRecords) -> str:
    cal = o.calendar or {}
    if not cal:
        return ""
    last = f", last {cal['lastDone']}" if cal.get("lastDone") else ""
    return f"jason deadlines: next {cal.get('next') or 'none'}, {cal.get('standing')}{last}"


def _recital_lines(recitals: Sequence[Recital]) -> list[str]:
    out = []
    for r in recitals:
        out.append(f"{r.rule.citation} ({r.rule.about})")
        if r.found:
            out.append(f"  \"{r.words}\"")
            out.append(f"  from {r.source}")
        else:
            out.append(f"  Its words are not on the authorities shelf ({r.reason}), so it is cited and not quoted.")
            if r.source:
                out.append(f"  looked in {r.source}")
        reach = ", ".join(r.reaches) or "no listed system"
        out.append(f"  a reading: by the row's condition ({r.rule.applies.describe()}) it reaches {reach}")
        out += [f"  question: {q}" for q in r.asks]
    return out


def lines(records: Records) -> list[str]:
    """The result as plain lines, a system at a time."""
    out: list[str] = []
    if not records.listed:
        out += ["The specification lists no life safety systems (Community.life_safety_systems()).", ""]
    for s in records.systems:
        system = s.system
        out.append(f"{system.name} ({system.kind.label})")
        if system.served():
            out.append(f"  serves: {system.served()}")
        for o in s.obligations:
            out.append(f"  {row_name(o.row)} ({cadence_of(o.row)})")
            if getattr(o.row, "authority", ""):
                out.append(f"    authority, as the row cites it: {o.row.authority}")
            if o.counted_from:
                out.append(f"    counted from {o.counted_from}, {o.counted_how}")
            else:
                out.append(f"    {o.counted_how}")
            if _calendar_text(o):
                out.append(f"    {_calendar_text(o)}")
            for period in o.periods:
                out += [f"    {line}" for line in _period_lines(period)]
            if o.earlier:
                out.append("    before the first period:")
                out += [f"      {_report_line(p)}" for p in o.earlier]
            if o.periods:
                out.append(f"    periods: {_counts_text(o)}")
        if not s.obligations:
            out.append("  no obligation with periods applies; nothing is expected of it here")
        if s.unassigned:
            out.append(f"  on file, not assigned to an obligation ({len(s.unassigned)})")
            for p, why in s.unassigned:
                out += [f"    {_report_line(p)}", f"      {why}"]
        if s.not_read:
            out.append(f"  filed, not read ({len(s.not_read)}): from a vendor the specification names for this system")
            out += [f"    {f.name} (sent {f.sent or 'undated'} by {f.vendor}; filed in {f.where or 'Drive'})" for f in s.not_read]
        if s.undetermined:
            out.append(f"  undetermined ({len(s.undetermined)})")
            for f in s.undetermined:
                out += [f"    {row_name(f.row)}", f"      question: {f.question()}"]
        if s.does_not_apply:
            out.append(f"  does not apply ({len(s.does_not_apply)}): nothing is expected")
            for why, findings in _why_groups(s.does_not_apply):
                out.append(f"    decided by {why}:")
                out += [f"      {row_name(f.row)}" for f in findings]
        out.append("")
    out.append(f"Unplaced ({len(records.unplaced)})")
    for u in records.unplaced:
        out += [f"  {u.label}", f"    {u.reason}"]
    if not records.unplaced:
        out.append("  none")
    if records.other_filings:
        out.append(f"  {records.other_filings} inspection report(s) in the filing log are from vendors no listed system "
                   "names, and are left out.")
    out += ["", "Record keeping"]
    out += [f"  {line}" for line in _recital_lines(records.recitals)] or ["  no record-keeping provision is listed"]
    if records.questions:
        out += ["", f"Questions for a person ({len(records.questions)})"]
        out += [f"  {q}" for q in records.questions]
    out.append("")
    out += [f"* {c}" for c in CAVEATS]
    return out


def markdown(records: Records) -> str:
    """The page ``--write`` saves: the same result in Markdown, under a header that says what it is."""
    name = records.community or "The association"
    out = [f"# Life safety records on file: {name}", "",
           f"Generated by jason on {date.today().isoformat()}, as of {records.as_of.isoformat()}, from the documents "
           "listed below. It is a summary, not the record: each line names the document it rests on, and the document "
           "governs.", ""]
    if records.sources:
        out += ["Read from: " + "; ".join(records.sources) + ".", ""]
    if not records.listed:
        out += ["The specification lists no life safety systems (`Community.life_safety_systems()`).", ""]
    if records.summary():
        out += ["## Summary", "", "| System | Obligation | Frequency | Covered | Partly on file | Not on file | Not yet due | Note |",
                "|---|---|---|---|---|---|---|---|"]
        names = {s.system.key: s.system.name for s in records.systems}
        for row in records.summary():
            out.append(f"| {names[row['system']]} | {row['obligation']} | {row['cadence']} | {row[Coverage.COVERED.value]} | "
                       f"{row[Coverage.PARTLY.value]} | {row[Coverage.NOT_ON_FILE.value]} | {row[Coverage.NOT_YET_DUE.value]} | "
                       f"{_cell(row['note'])} |")
        out.append("")
    for s in records.systems:
        system = s.system
        out += [f"## {system.name}", "", f"A {system.kind.label}" + (f", serving {system.served()}." if system.served() else "."), ""]
        for o in s.obligations:
            out += [f"### {row_name(o.row)}", "", f"- Frequency: {cadence_of(o.row)}"]
            if getattr(o.row, "authority", ""):
                out.append(f"- Authority, as the row cites it: {o.row.authority}")
            out.append(f"- Counted from {o.counted_from}, {o.counted_how}." if o.counted_from else f"- {o.counted_how}")
            if _calendar_text(o):
                out.append(f"- {_calendar_text(o)}")
            out.append("")
            if o.periods:
                out += ["| Period | Standing | On file |", "|---|---|---|"]
                for p in o.periods:
                    held = [_report_line(r) for r in p.reports] + [c.label for c in p.completions]
                    if p.missing:
                        held.append(f"nothing on file for building {', '.join(p.missing)}")
                    if p.note:
                        held.append(p.note)
                    out.append(f"| {p.label} | {p.status.value} | {'<br>'.join(_cell(h) for h in held) or 'nothing'} |")
                out.append("")
            if o.earlier:
                out += ["Before the first period:", ""] + [f"- {_report_line(p)}" for p in o.earlier] + [""]
        if not s.obligations:
            out += ["No obligation with periods applies; nothing is expected of it here.", ""]
        if s.unassigned:
            out += ["### On file, not assigned to an obligation", ""]
            out += [f"- {_report_line(p)}. {why}." for p, why in s.unassigned] + [""]
        if s.not_read:
            out += ["### Filed, not read", "", "From a vendor the specification names for this system; no reader has "
                    "read them, so none is placed in a period.", ""]
            out += [f"- {f.name} (sent {f.sent or 'undated'} by {f.vendor}; filed in {f.where or 'Drive'})" for f in s.not_read] + [""]
        if s.undetermined:
            out += ["### Undetermined", ""]
            out += [f"- {row_name(f.row)}: {f.question()}" for f in s.undetermined] + [""]
        if s.does_not_apply:
            out += ["### Does not apply", "", "Nothing is expected for these, and the fact that decided each is named.", ""]
            for why, findings in _why_groups(s.does_not_apply):
                out.append(f"- Decided by {why}: " + "; ".join(row_name(f.row) for f in findings))
            out.append("")
    out += ["## Unplaced", ""]
    out += [f"- {u.label}: {u.reason}" for u in records.unplaced] or ["None."]
    if records.other_filings:
        out.append(f"- {records.other_filings} inspection report(s) in the filing log are from vendors no listed system "
                   "names, and are left out.")
    out += ["", "## Record keeping", ""]
    for r in records.recitals:
        out.append(f"**{r.rule.citation}** ({r.rule.about})")
        out.append("")
        if r.found:
            out += [f"> \"{r.words}\"", "", f"From {r.source}."]
        else:
            out.append(f"Its words are not on the authorities shelf ({r.reason}), so it is cited and not quoted.")
        out.append(f"A reading: by the row's condition ({r.rule.applies.describe()}) it reaches "
                   f"{', '.join(r.reaches) or 'no listed system'}.")
        out += [f"Question: {q}" for q in r.asks]
        out.append("")
    if records.questions:
        out += ["## Questions for a person", ""] + [f"- {q}" for q in records.questions] + [""]
    out += ["## How to read this page", ""] + [f"- {c}" for c in CAVEATS] + [""]
    return "\n".join(out)


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def write(data_dir: Path | str, records: Records) -> Path:
    """Save the page under the data root (``reports/life-safety-records.md``), holding its store lock."""
    from jason.locks import Resource, hold

    path = Path(data_dir) / PAGE
    with hold(Resource.STORE, LOCK_KEY, timeout=120, purpose="jason inspections --write"):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(markdown(records), encoding="utf-8")
    return path


__all__ = ["CAVEATS", "Completion", "Coverage", "Filing", "ObligationRecords", "PAGE", "Period", "Placed", "Recital",
           "Records", "Report", "SYSTEM_WORDS", "SystemRecords", "Unplaced", "completeness", "lines", "markdown",
           "months_of", "obligation_for", "place", "recite", "review", "slots_of", "write"]
