"""jason's base notice templates checked against the law: each required element present or missing, and each sentence
that states the law in the template's own words, with the reference that would recite it.

The bases checked are the ones a notice in the catalog (``jason.community.notice_catalog``) is drafted from:

- the rule change notices (4360(a), (c)), generated by ``jason.tasks.rule_change`` (checked as rendered for a made-up
  change);
- the hearing notice (5855) and the board meeting agenda (4920), the letter bodies in ``jason.community.templates``;
- the annual policy statement (5310), the annual budget report (5300), and the insurance change notice (5810), the
  packet bases in ``src/jason/templates/packets``;
- the pre-lien notice (5660), which has no base yet: every element is missing until one is written.

A base keeps its tokens (``{HEARING_DATE}``): an element a token supplies is reported as such, and filled when the
notice is. Reading only; ``report_lines`` is the page ``jason notice-check`` writes to ``data/reports``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Callable

from jason.community.notice_catalog import requirement
from jason.community.notice_elements import (STATUTE_TOKEN_NOTE, ElementFinding, LawStatement, Status, check,
                                             law_statements)

PACKETS = Path(__file__).resolve().parents[1] / "templates" / "packets"
REPORT = "notice-templates.md"
EXAMPLE_ASSOCIATION = "Example Commons Owners Association"


@dataclass(frozen=True)
class BaseTemplate:
    """A base template and the catalog requirement it serves. ``where`` names it for a person; ``load`` reads it with
    its tokens kept (None: no base exists yet)."""

    requirement: str
    title: str
    where: str
    load: Callable[[], str] | None = None


def _example_change():
    from jason.community.rule_changes import RuleChange, SectionChange

    return RuleChange(
        key="example", title="Example change", document="example-rules", document_title="Example Rules",
        purpose="To say when the pool opens.", effect="The pool opens at [opening hour] instead of 8 a.m.",
        sections=(SectionChange("1", "Pool Hours.", strike="8 a.m.", proposed="[opening hour]"),
                  SectionChange("2", "Guests.", proposed="Each unit may bring two guests.")))


def _example_timeline():
    from jason.tasks import rule_change as rc

    return rc.timeline(None, notice_date=date(2099, 1, 1), decision=date(2099, 2, 3))


def _member_notice() -> str:
    from jason.tasks import rule_change as rc

    return rc.member_notice(_example_change(), _example_timeline(), {}, EXAMPLE_ASSOCIATION).text


def _adoption_notice() -> str:
    from jason.tasks import rule_change as rc

    return rc.adoption_notice(_example_change(), _example_timeline(), EXAMPLE_ASSOCIATION).text


def _body(kind_name: str) -> Callable[[], str]:
    def load() -> str:
        from jason.community.templates import BODIES, TemplateKind, body_markdown, tokens_in

        kind = TemplateKind[kind_name]
        names = tokens_in("\n".join(text for _, text in BODIES[kind]))
        return body_markdown(kind, {n: "{" + n + "}" for n in names})
    return load


def _notice_base() -> str:
    from jason.tasks.meeting_notice import base_text

    return base_text()


def _packet(name: str) -> Callable[[], str]:
    return lambda: (PACKETS / name).read_text(encoding="utf-8")


BASES: tuple[BaseTemplate, ...] = (
    BaseTemplate("rule-change-proposed", "Notice of proposed rule change", "jason.tasks.rule_change.member_notice",
                 _member_notice),
    BaseTemplate("rule-change-adopted", "Notice of adopted rule change", "jason.tasks.rule_change.adoption_notice",
                 _adoption_notice),
    BaseTemplate("discipline-hearing", "Notice of hearing", "jason.community.templates.BODIES[HEARING_NOTICE]",
                 _body("HEARING_NOTICE")),
    BaseTemplate("board-meeting", "Board meeting agenda (the notice's agenda and teleconference statements)",
                 "jason.community.templates.BODIES[AGENDA]", _body("AGENDA")),
    BaseTemplate("board-meeting", "Notice of board meeting (every format's block)",
                 "src/jason/templates/notices/board-meeting-notice.md", _notice_base),
    BaseTemplate("annual-policy-statement", "Annual policy statement", "src/jason/templates/packets/"
                 "annual-policy-statement.md", _packet("annual-policy-statement.md")),
    BaseTemplate("annual-budget-report", "Annual budget report", "src/jason/templates/packets/annual-budget-report.md",
                 _packet("annual-budget-report.md")),
    BaseTemplate("insurance-change", "Insurance change notice", "src/jason/templates/packets/"
                 "insurance-change-notice.html", _packet("insurance-change-notice.html")),
    BaseTemplate("pre-lien-notice", "Pre-lien notice", "(no base template; the 5660 checklist is in "
                 "jason.community.models.legal_collections)", None),
)


@dataclass
class TemplateCheck:
    base: BaseTemplate
    findings: list[ElementFinding]
    law: list[LawStatement]
    error: str = ""

    @property
    def missing(self) -> list[ElementFinding]:
        return [f for f in self.findings if f.status is Status.MISSING]


def check_base(base: BaseTemplate, facts: Any = None) -> TemplateCheck:
    """``facts`` are the event's facts as the caller has them (``jason.community.applicability.Facts``); without them
    a conditional element stays undetermined, and is reported with its condition."""
    row = requirement(base.requirement)
    if base.load is None:
        return TemplateCheck(base, check(row, "", facts), [], "no base template")
    try:
        text = base.load()
    except Exception as exc:          # a base that cannot be read is a finding, not a crash
        return TemplateCheck(base, check(row, "", facts), [], f"could not read: {exc}")
    return TemplateCheck(base, check(row, text, facts), law_statements(text))


def check_all(keys: tuple[str, ...] = (), facts: Any = None) -> list[TemplateCheck]:
    return [check_base(b, facts) for b in BASES if not keys or b.requirement in keys]


def check_file(path: Path, key: str, facts: Any = None) -> TemplateCheck:
    """A rendered notice (a draft, a filled letter) against one requirement."""
    text = Path(path).read_text(encoding="utf-8")
    base = BaseTemplate(key, Path(path).name, str(path), lambda: text)
    return check_base(base, facts)


def recite(citations: tuple[str, ...], shelf: Any) -> dict[str, tuple[bool, str]]:
    """Each cited subdivision's words from disk through the shared reader: (found, the words or why not)."""
    out: dict[str, tuple[bool, str]] = {}
    for c in citations:
        try:
            got = shelf(c)
            words = got.text if got.found else (got.reason.value if got.reason else "not found")
            if got.found and words.lstrip().startswith("- History"):
                # A whole section as exported: its history line and the session note come before its words.
                words = re.sub(r"^.*?\n\s*\d{3,4}(?:\.\d+)?\.\s*\([^)]*\)\s*", "", words, count=1, flags=re.S)
            out[c] = (got.found, words)
        except Exception as exc:
            out[c] = (False, str(exc))
    return out


def _cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "/")


def report_lines(checks: list[TemplateCheck], *, shelf: Any = None, law: bool = True) -> list[str]:
    lines = ["# Base notice templates against the law", "",
             "_Each required element is the catalog's reading of the statute (`jason notices KEY --catalog`); the check "
             "is a reading of words, not of law, and a person reads the notice before it goes out. A token "
             "(`{HEARING_DATE}`) supplies its element when the notice is filled._", "",
             "| Requirement | Base | Present | Token | Enclosed | Missing | Unchecked |", "|---|---|---|---|---|---|---|"]
    for c in checks:
        count = {s: sum(1 for f in c.findings if f.status is s) for s in Status}
        lines.append(f"| `{c.base.requirement}` | {c.base.title}{' (' + c.error + ')' if c.error else ''} | "
                     f"{count[Status.PRESENT]} | {count[Status.TOKEN]} | {count[Status.ENCLOSED]} | "
                     f"{count[Status.MISSING]} | {count[Status.UNCHECKED]} |")
    for c in checks:
        row = requirement(c.base.requirement)
        lines += ["", f"## `{c.base.requirement}`: {c.base.title}", "", f"Base: `{c.base.where}`. Statute: "
                  f"{row.statute}." + (f" **{c.error}.**" if c.error else ""), ""]
        for f in c.findings:
            cond = f" ({f.condition()})" if f.applies and not f.ok and f.required is not False else ""
            lines.append(f"- **{f.status.value}**{cond}: {f.element} ({f.cite})" + (f"; {f.where}" if f.where else ""))
        statements = [s for s in c.law if not s.heading]
        named = [x for s in c.law if s.heading for x in s.citations]
        if law and named:
            lines += ["", "Headings and bare citations name: " + ", ".join(dict.fromkeys(named)) + " (a `{CITE:}` each, "
                      "once statute targets are tokens)."]
        if law and statements:
            lines += ["", "Where the base states the law in its own words (the reading), the statute's words on disk "
                          "(the rule, recited below), and the reference that would cite it:", "",
                      "| Line | The base says | Cites | On disk | Proposed reference |", "|---|---|---|---|---|"]
            for s in statements:
                found = recite(s.citations, shelf) if shelf is not None else {}
                disk = "; ".join(f"{k}: {'yes' if v[0] else 'no (' + v[1] + ')'}" for k, v in found.items())
                lines.append(f"| {s.line} | {_cell(s.sentence)[:200]} | {', '.join(s.citations)} | {disk or 'not read'} "
                             f"| {' '.join(s.tokens)} |")
    if law:
        lines += ["", f"_{STATUTE_TOKEN_NOTE}_"]
    return lines


def recitals_lines(checks: list[TemplateCheck], shelf: Any) -> list[str]:
    """The statute's words for each subdivision the bases cite, once each: the rule beside the bases' readings."""
    seen: dict[str, None] = {}
    for c in checks:
        for s in c.law:
            if s.heading:
                continue
            for x in s.citations:
                seen.setdefault(x, None)
    lines = ["", "## The statutes the bases cite, recited from data/authorities", ""]
    for c, (ok, words) in recite(tuple(seen), shelf).items():
        if ok:
            text = " ".join(words.split())
            lines += [f"**{c}:** \"{text[:700]}{' ...' if len(text) > 700 else ''}\"", ""]
        else:
            lines += [f"**{c}:** not on disk ({words}).", ""]
    return lines


def write(data_dir: Path, lines: list[str]) -> Path:
    path = Path(data_dir) / "reports" / REPORT
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path


__all__ = ["BASES", "BaseTemplate", "TemplateCheck", "check_all", "check_base", "check_file", "recitals_lines",
           "recite", "report_lines", "write"]
